name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up latest uv and Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: true
    - name: Install / build
      run: |
        uv pip install .

  test:
    name: test (ubuntu-latest, ${{ matrix.python-version }}, packages version ${{ matrix.resolution }})
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        resolution: ["highest", "lowest-direct"]
    steps:
    - uses: actions/checkout@v7
    - name: Install uv and Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: true
    - name: Install dependencies
      run: |
        uv sync --resolution ${{matrix.resolution}} --no-group docs --group test
    - name: Test with pytest
      run: |
        uv run --no-sync pytest xnemogcm/test
